Updated UI with bulma swatches
facet-acq/post-award pull request #49
Opened 2018-03-02 04:18 UTC by pmakarov

# Pull Request

## Purpose

Fixed UI and layout by adding custom styles and using bulmaswatch

## Approach

Help keep the story going.

- What decisions did you make?
- Anything really cool of which you're proud?
- Anything you want to call out as 'works for now, should look at more thought'?

## Lessons Learned
Added proper relative pathing to the node_modules in sass by using the webpack convetion of '~bulma/' as an example.  Added Sass pathing to font awesome assets for webpack using new syntax: $fa-font-path: "~font-awesome/fonts" !default; 

Learned about bulmaswatch npm package and how to toggle different themes and apply different styles.

Think about:

- Patterns used
- Libraries
- Framework features/new dependencies
- Tutorials

2018-03-03 14:07 UTC, djfurman requested changes
I added a few comments for a few of the files below. Looks great overall and I like the bulma swatches addition a lot.

If you could please take a look at the `.vscode` directory commit and the `.env.example` I'm happy to accept it.

Thanks for the PR!

2018-03-03 14:07 UTC, djfurman commented on .env.example
> -APP_NAME=Laravel
Might be a good thing to add `use cp .env.example .env` to the setup documentation.

Also, would you please add this example file back into the repo? I'd prefer not to delete it.

2018-03-03 14:07 UTC, djfurman commented on .eslintrc.json
> -{
Did the `eslintrc.json` file cause conflicts? I'd prefer it to stay there for config of eslint for CI unless we have a reason to kill it

2018-03-03 14:07 UTC, djfurman commented on .vscode/launch.json
> +{
We should consider adding `.vscode` to the `.gitinore` file. For now can you remove it from your commit? The IDE config shouldn't be part of the coding project.

2018-03-03 14:07 UTC, djfurman commented on .vscode/settings.json
> +{
Same IDE config comment above. Please remove from your PR

2018-03-03 14:07 UTC, djfurman commented on package.json
> +        "bulmaswatch": "^0.6.2",
Do these need to be dependencies or is it okay to make them dev dependencies?

2018-03-03 14:07 UTC, djfurman commented on resources/assets/js/components/FacetLandingPage.vue
> +    <!-- <div class="container is-fluid">
Feel free to delete this stuff instead of commenting it out

2018-03-03 14:07 UTC, djfurman commented on resources/assets/js/components/NavBar.Vue
> +  <!-- <nav class="navbar is-primary is-fixed-top" role="navigation" aria-label="main navigation">
Feel free to remove this as well instead of commenting it out

2018-03-03 14:07 UTC, djfurman commented on resources/assets/sass/app.scss
> +$fa-font-path: "~font-awesome/fonts" !default;
what does `!default` do? I'm not overly familiar with scss

2018-03-03 14:07 UTC, djfurman commented on resources/assets/sass/app.scss
> +@import '~font-awesome/scss/font-awesome.scss';
I love not having to path this!

2018-03-03 14:07 UTC, djfurman commented on resources/assets/js/components/App.vue
> +    <!-- <section class="hero is-light is-bold">
feel free to delete if this section is replaced, where does the section tag end at this point?

2018-04-07 02:37 UTC, djfurman commented
@pmakarov I'm still very interested in your PR if you have a few moments to take a look at this feedback

Keep rocking! 😎

2018-04-10 01:51 UTC, pmakarov commented on .env.example
> -APP_NAME=Laravel
added the default laravel .env.example back

2018-04-10 01:51 UTC, pmakarov commented on .eslintrc.json
> -{
not sure where this one went, I did a local revert to get the file back, enjoy

2018-04-10 01:52 UTC, pmakarov commented on .vscode/launch.json
> +{
I modified my .gitignore to include .vscode/

2018-04-10 01:52 UTC, pmakarov commented on package.json
> +        "bulmaswatch": "^0.6.2",
I moved them to dev dependencies

2018-04-10 01:52 UTC, pmakarov commented on resources/assets/js/components/FacetLandingPage.vue
> +    <!-- <div class="container is-fluid">
deleting out as convenient...

2018-04-23 22:40 UTC, djfurman commented
Running as a traditional merge given rebase conflicts; will disable merge based in favor of rebase in the future.

2018-04-23 22:40 UTC, merged